CallbackReturn Fix
ros-controls/ros2_control_demos pull request #173
Opened 2022-04-18 21:54 UTC by kutlayacar

I have fixed "CallbackReturn" as it mentioned in this [Issue](https://github.com/ros-controls/ros2_control_demos/issues/171).

2022-04-19 02:25 UTC, homalozoa commented
Hi @kutlayacar . Thanks for you contribution. It seems you have added `.idea` folder to this change, please remove it and push again. Thank you.

2022-04-19 02:25 UTC, homalozoa requested changes
Remove `.idea`, please.

2022-04-19 02:27 UTC, harderthan approved these changes

2022-04-19 06:09 UTC, kutlayacar commented
Hi @homalozoa. Sorry for my mistake. I have deleted .idea folder and pushed again. Thank you.

2022-04-19 06:19 UTC, homalozoa approved these changes
LGTM. Thanks @kutlayacar

2022-04-19 06:27 UTC, arne48 approved these changes
With the .idea clean-up this should be a good fix for #171 
Thank you very much :)

2022-04-19 07:05 UTC, kutlayacar commented
Thank you!

2022-04-19 19:45 UTC, destogl requested changes
Thanks for the contribution!

You should also update `CallbackReturn` to `hardware_interface::CallbackReturn` in the hardware.

2022-04-19 20:17 UTC, kutlayacar commented
You're welcome! 

I guess it should work now. I have forgotten to fix the `CallbackReturn` to `hardware_interface::CallbackReturn` in the .hpp files.

2022-04-20 10:49 UTC, destogl approved these changes
Thanks!!!

2022-04-20 10:49 UTC, destogl commented on ros2_control_demo_hardware/include/ros2_control_demo_hardware/diffbot_system.hpp
```suggestion
```

2022-04-20 10:49 UTC, destogl commented on ros2_control_demo_hardware/include/ros2_control_demo_hardware/external_rrbot_force_torque_sensor.hpp
```suggestion
```

2022-04-20 10:49 UTC, destogl commented on ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_actuator.hpp
```suggestion
```

2022-04-20 10:49 UTC, destogl commented on ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_multi_interface.hpp
```suggestion
```

2022-04-20 10:49 UTC, destogl commented on ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_position_only.hpp
```suggestion
```

2022-04-20 10:49 UTC, destogl commented on ros2_control_demo_hardware/include/ros2_control_demo_hardware/rrbot_system_with_sensor.hpp
```suggestion
```

2022-04-20 12:10 UTC, destogl commented
@kutlayacar can you please fix formatting? (you can use "pre-commit" command in your local repository to do this automatically. (check the internet for starting manuals)

2022-04-20 16:09 UTC, kutlayacar commented
> @destogl I am on it!
I have used your .clang-format file to format the code and pushed it. I hope it works like this. Otherwise I need from you a detailed information. Thank you and I am sorry for these issues.

2022-04-20 16:33 UTC, kutlayacar commented
> > @destogl I am on it!
> 
> I have used your .clang-format file to format the code and pushed it. I hope it works like this. Otherwise I need from you a detailed information. Thank you and I am sorry for these issues.

So it didn't work properly. I'll commit it again as soon as possible, when I fix it.

2022-04-20 21:54 UTC, kutlayacar commented
Hello again, 

the code passed the clang-format test on my local repository. I have committed the changes and hope it works now with no issues. 

Best wishes

2022-04-21 08:11 UTC, merged