Add example of starting controllers with launch files
ros-controls/ros2_control_demos pull request #273
Opened 2023-04-18 08:16 UTC by christophfroehlich

Rewrite of #66

2023-05-01 20:25 UTC, destogl requested changes
I like the docs extension and showing how controllers are managed. Nevertheless, I am not convinced that we need this launch file. We have great CLI options, and they can do everything required, so what is the added value into having this launch file.

@v-lopez if you are still there, please tell us.

Still, @bmagyar and @christophfroehlich, what do you think about his additional option? Is there something I don't see?

2023-05-01 20:25 UTC, destogl commented on example_1/doc/userdoc.rst
> +      what should return ``Successfully loaded controller joint_trajectory_position_controller``. Check the status
```suggestion
      what should return ``Successfully loaded controller joint_trajectory_position_controller``.
      Then check controllers' status
```

2023-05-01 20:25 UTC, destogl commented on example_1/doc/userdoc.rst
> +      what shows you that the controller is loaded but unconfigured.
```suggestion
      what shows you that the controller is loaded but unconfigured. Similar output is expected:
```

2023-05-02 07:27 UTC, christophfroehlich commented
The diff view is broken here, this PR actually only adds literal c in line 167. The rest is just restructuring of the section.

I found the old PR interesting and merged it to the new structure. I thought it could be helpful for switching controller from some external interface like a GUI, or probably shows how to integrate `controller_manager.launch_utils` to a python state machine script. But because it only loads the controller but does not activate it, I agree that the benefit of this launch file is close to zero.

2023-07-01 09:29 UTC, olivier-stasse approved these changes
For a first example I believe that the most simple example is preferable.
We can give a try but I think most of the feedback we had was that simpler is better.

2023-07-01 11:53 UTC, christophfroehlich commented
I don't have any hard feelings about this PR. If you think this is not adding any value to the demos but only making them more verbose -> I'll close it.

2023-07-01 11:53 UTC, closed without merging