reserving example 11
ros-controls/ros2_control_demos pull request #316
Opened 2023-06-20 22:03 UTC by ARK3r

2023-06-29 22:31 UTC, ARK3r commented
After running `carlikebot.launch.py` I get the following:
```bash
TF_NAN_INPUT: Ignoring transform for child_frame_id "rear_left_wheel" from authority "Authority undetectable" because of a nan value in the transform (nan nan nan) (nan nan nan nan)
[rviz2-5]          at line 235 in ./src/buffer_core.cpp
[rviz2-5] Error:   TF_DENORMALIZED_QUATERNION: Ignoring transform for child_frame_id "rear_left_wheel" from authority "Authority undetectable" because of an invalid quaternion in the transform (nan nan nan nan)
[rviz2-5]          at line 254 in ./src/buffer_core.cpp
[rviz2-5] Error:   TF_NAN_INPUT: Ignoring transform for child_frame_id "rear_right_wheel" from authority "Authority undetectable" because of a nan value in the transform (nan nan nan) (nan nan nan nan)
[rviz2-5]          at line 235 in ./src/buffer_core.cpp
[rviz2-5] Error:   TF_DENORMALIZED_QUATERNION: Ignoring transform for child_frame_id "rear_right_wheel" from authority "Authority undetectable" because of an invalid quaternion in the transform (nan nan nan nan)
[rviz2-5]          at line 254 in ./src/buffer_core.cpp
```

And these are the outputs from the launch file.

```bash
reza@3d65c5cee69c:/home/ws$ ros2 control list_hardware_interfaces 
command interfaces
        ackermann_steering_controller/angular/position [unavailable] [unclaimed]
        ackermann_steering_controller/linear/velocity [unavailable] [unclaimed]
        left_steering_joint/position [available] [unclaimed]
        rear_left_wheel_joint/velocity [available] [unclaimed]
        rear_right_wheel_joint/velocity [available] [unclaimed]
        right_steering_joint/position [available] [unclaimed]
state interfaces
        left_steering_joint/position
        rear_left_wheel_joint/velocity
        rear_right_wheel_joint/velocity
        right_steering_joint/position
reza@3d65c5cee69c:/home/ws$ ros2 control list_controllers 
joint_state_broadcaster[joint_state_broadcaster/JointStateBroadcaster] active    
ackermann_steering_controller[ackermann_steering_controller/AckermannSteeringController] inactive  
```

I've cross-checked this package with the Diffbot package (example_2) and I can't figure out where the issue is coming from.

2023-06-30 09:37 UTC, christophfroehlich commented
The problem is that the joint_states do not have finite values
```
$ ros2 topic echo /joint_states
header:
  stamp:
    sec: 1688117758
    nanosec: 551043008
  frame_id: ''
name:
- left_steering_joint
- right_steering_joint
- rear_left_wheel_joint
- rear_right_wheel_joint
position:
- 0.0
- 0.0
- .nan
- .nan
velocity:
- .nan
- .nan
- 0.0
- 0.0
effort:
- .nan
- .nan
- .nan
- .nan
```

2023-06-30 16:11 UTC, ARK3r commented
Thank you that solved it.

Does this mean that if a motor doesn't have positional reading, it is mandatory for the data to be augmented (by calculating speed * time)?

2023-06-30 17:07 UTC, christophfroehlich commented
Yes and no. There has to be a valid position value in the joint_states message, but if you don't care that the wheels aren't rotating in rviz2 then you also can send zeros.

2023-08-20 12:35 UTC, christophfroehlich commented
@ARK3r are there any updates on this, or are you waiting on feedback?

2023-09-21 19:29 UTC, ARK3r commented
@christophfroehlich it got pushed to the side, I'll try to wrap it up soon. 

If you could take a look at the structure of it all, next I'll add some docs.

2023-09-27 17:40 UTC, ARK3r commented
Comparing the behaviour of DiffBot and CarlikeBot I'm seeing some differences and I'm wondering if this is coming from the controllers or the configuration.

DiffBot
![DiffBot](https://github.com/ros-controls/ros2_control_demos/assets/22005547/9cdd2437-6e43-4a19-b9e4-96e2f4a76182)

CarlikeBot:
![CarlikeBot](https://github.com/ros-controls/ros2_control_demos/assets/22005547/a8499f4a-7b61-4f80-8f72-a9e7915e9678)

2023-09-29 07:39 UTC, christophfroehlich commented
@ARK3r the example looks fine and works now (I just made small fixes to simplify the launch file), but I also observe the strange behavior of the controller. With twist with smaller magnitude it starts fine but ends in a spiral instead of a circle.

2023-09-29 07:51 UTC, christophfroehlich requested changes

2023-09-29 07:51 UTC, christophfroehlich commented on example_11/hardware/carlikebot_system.cpp
> +  }
I think the problem comes from this part of the code: steering command is position (angle), and not a velocity.

2023-10-03 21:43 UTC, ARK3r commented
The last change I made still doesn't fix the issue, but I think it's a step closer by putting all the interfaces in one vector with type tuple<string, double, double> for joint name, state, and command.

Also by taking a look at [this](https://github.com/ros-controls/ros2_controllers/blob/master/ackermann_steering_controller/doc/userdoc.rst), I noticed that for the rear, two wheels are expected, with each accepting one command, and for steering, two wheels are expected with each taking **two** commands. Does this mean I need to add separate joints and links to each steering hinge on the front for the wheels so that the rotation of the wheels can accept a command as well?

2023-10-03 21:46 UTC, christophfroehlich commented
no it expects 4 command interfaces only as far as I can remember. I'll have a look on that somewhen the next days, maybe also fixing the bug with the open_loop mode first.

2023-10-09 16:28 UTC, christophfroehlich commented
The launch file is not working since the last commits?

I added a PR to fix the open_loop mode, maybe this helps you with debugging: https://github.com/ros-controls/ros2_controllers/pull/793

2024-01-02 10:06 UTC, christophfroehlich requested changes
There is an issue in the URDF: the traction joint of the front wheels has wrong axis.
![image](https://github.com/ros-controls/ros2_control_demos/assets/3367244/859cb8c8-d481-49e0-bf34-88bc626ad525)

2024-01-04 07:31 UTC, nice-user1 commented
There is some transform error with this. when running example_11 "carlikebot.launch.py", only robot body is visible and the wheels are not. I have attached the log file below. The error starts from line number 78.
[error.txt](https://github.com/ros-controls/ros2_control_demos/files/13827349/error.txt)

2024-01-26 22:15 UTC, ARK3r commented
Here I changed the carlikebot description a little so that I can use the bicycle controller on a 4-wheel vehicle. There are two virtual joints, one for steering and one for traction where carlikebot's actual wheels just mimic the movements of the virtual joints. I think this will be a good baseline for using ackermann on the same urdf with minor changes and adding a couple of arguments to the xacro and launch files.

I have yet to fix the documentation but everything should be functional so I would appreciate it if you could give it a try. I also made some design changes by defining a map for hw_interfaces_ instead of a vector. I believe this will make the code way more readable.

2024-01-26 22:22 UTC, ARK3r commented
One strange thing I'm noticing is when `linear.x=0`, whatever value `angular.z` gets the steering just snaps to $\pm \pi$ which I believe comes from [SteeringOdodmetry::get_commands](https://github.com/ros-controls/ros2_controllers/blob/humble/steering_controllers_library/src/steering_odometry.cpp#L218-L222). I'm just not sure what the reason for this is and it feels strange. Wonder if anyone has an explanation.

2024-02-06 21:09 UTC, ARK3r commented
> There is an issue in the URDF: the traction joint of the front wheels has wrong axis. ![image](https://private-user-images.githubusercontent.com/3367244/293668158-859cb8c8-d481-49e0-bf34-88bc626ad525.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNTQwNDQsIm5iZiI6MTcwNzI1Mzc0NCwicGF0aCI6Ii8zMzY3MjQ0LzI5MzY2ODE1OC04NTljYjhjOC1kNDgxLTQ5ZTAtYmYzNC04OGJjNjI2YWQ1MjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMjEwOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGRjZGYzODFiMzJlZTc5YzFlOGYyODNlNTE2ZGJmMjcwZTYxYjQ5NDhhZTZiMjI0NDc3ZGNhMTI0NTQyNzU2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.l2OFmgeoXkRcU_QJxfP2r9XAL6RRVXffFE_83wrlcm8)

this issue is now resolved with the new description.

2024-02-17 16:55 UTC, christophfroehlich approved these changes
> One strange thing I'm noticing is when `linear.x=0`, whatever value `angular.z` gets, the steering just snaps to ±π which I believe comes from [SteeringOdodmetry::get_commands](https://github.com/ros-controls/ros2_controllers/blob/humble/steering_controllers_library/src/steering_odometry.cpp#L218-L222). I'm just not sure what the reason for this is and it feels strange. Wonder if anyone has an explanation.

I think this is fine, because this is a singular point of the inverse kinematics. It would be also fine if the bicycle controller does not accept it, because this does not work with the traction wheel not being the steered one (but with the [tricycle model](http://localhost:8081/doc/ros2_controllers/tricycle_controller/doc/userdoc.html) it would work).



> > There is an issue in the URDF: the traction joint of the front wheels has wrong axis.  
>
> this issue is now resolved with the new description.

Perfect.

> Here I changed the carlikebot description a little so that I can use the bicycle controller on a 4-wheel vehicle. There are two virtual joints, one for steering and one for traction where carlikebot's actual wheels just mimic the movements of the virtual joints. I think this will be a good baseline for using ackermann on the same urdf with minor changes and adding a couple of arguments to the xacro and launch files.

I'm fine with that. This also is aligned with my nomenclature of https://github.com/ros-controls/ros2_controllers/pull/954 (I'd be happy about some feedback there).

> Also I added a node to relay the /tf_odometry topic to /tf which you can activate by calling `ros2 launch ros2_control_demo_example_11 carlikebot.launch.py relay_odometry_tf:=true`

I changed this to use remapping instead, to avoid a dependency on topic_tools.

2024-02-17 16:56 UTC, christophfroehlich commented
@mergifyio backport iron humble

2024-02-17 17:02 UTC, merged