[Example 15] Using multiple controller managers under different namespaces
ros-controls/ros2_control_demos pull request #423
Opened 2023-12-25 22:16 UTC by christophfroehlich

A rewrite of #170 including https://github.com/StoglRobotics-forks/ros2_control_demos/pull/8

2023-12-27 05:35 UTC, saikishor requested changes
LGTM. The tutorial works too.

Thank you

2023-12-27 05:35 UTC, saikishor commented on README.md
> +   This example shows how to include multiple robots in namespaced controller manager instances.
```suggestion
* Example 14: ["Modular robots with actuators not providing states and with additional sensors"](example_14)

   The example shows how to implement robot hardware with actuators not providing states and with additional sensors.

* Example 15: ["Using multiple controller managers"](example_15)

   This example shows how to integrate multiple robots under different controller manager instances.
```

2023-12-27 05:35 UTC, saikishor commented on doc/index.rst
> +   This example shows how to include multiple robots in namespaced controller manager instances.
```suggestion
Example 15: "Using multiple controller managers"
   This example shows how to integrate multiple robots under different controller manager instances.
```

2023-12-27 05:35 UTC, saikishor commented on doc/index.rst
> +   Example 15: Using multiple controller managers under different namespaces <../example_15/doc/userdoc.rst>
```suggestion
   Example 15: Using multiple controller managers <../example_15/doc/userdoc.rst>
```

2023-12-27 05:35 UTC, saikishor commented on example_15/README.md
> +   This example shows how to include multiple robots in namespaced controller manager instances.
```suggestion
   This example shows how to integrate multiple robots under different controller manager instances.
```

2023-12-27 05:35 UTC, saikishor commented on example_15/doc/userdoc.rst
> +This example shows how to include multiple robots in namespaced controller manager instances.
```suggestion
This example shows how to integrate multiple robots under different controller manager instances.
```

2023-12-27 05:35 UTC, saikishor commented on example_15/doc/userdoc.rst
> +=========================================================================
```suggestion
Example 15: Using multiple controller managers
==============================================
```

2023-12-27 05:35 UTC, saikishor commented on example_15/doc/userdoc.rst
> +----------------------------------------------------------------
```suggestion
Scenario: Using ros2_control within a local namespace
-----------------------------------------------------
```

2023-12-27 05:35 UTC, saikishor commented on example_15/doc/userdoc.rst
> +-------------------------------------------------------------------------
```suggestion
Scenario: Using multiple controller managers on the same machine
----------------------------------------------------------------
```

2023-12-27 12:32 UTC, christophfroehlich commented
> LGTM. The tutorial works too. Just some minor changes.
> 
> Thank you

thx. what do you think about the two questions in the PR description?

2024-05-28 18:15 UTC, olivier-stasse approved these changes
Thanks a lot for this great example.
Tested on my machine (22.04 LTS + head of ros2_control and ros2_controllers)

2024-05-28 18:57 UTC, olivier-stasse commented
I don't understand which change is missing from @saikishor review.

2024-05-28 19:00 UTC, christophfroehlich commented
> I don't understand which change is missing from @saikishor review.

Thanks for your review. I addressed his comments, only the final approval was missing.

2024-05-28 19:01 UTC, merged