Update all demos using the description from topic rather than the parameter
ros-controls/ros2_control_demos pull request #456
Opened 2024-02-29 19:38 UTC by fmauch

This will make sure things work after https://github.com/ros-controls/ros2_control/pull/1358 is merged.

I'll update this demo by demo whenever I find the time and check the demos according to their docs after modifying them.

2024-03-02 22:57 UTC, saikishor requested changes

2024-03-02 22:57 UTC, saikishor commented on example_14/hardware/rrbot_actuator_without_feedback.cpp
> +  if (!std::isnan(hw_joint_command_))
```suggestion
  if (std::isfinite(hw_joint_command_))
```

May be `isfinite` is better here as it handles both `NaN` and `Infinity`

2024-03-02 23:24 UTC, fmauch commented
Migrated all demos and manually tested them.

2024-03-02 23:34 UTC, saikishor approved these changes
The changes look good to me!

Let's merge once https://github.com/ros-controls/ros2_control/pull/1358 is merged!

2024-03-03 10:13 UTC, fmauch commented
> The changes look good to me!
> 
> Let's merge once [ros-controls/ros2_control#1358](https://github.com/ros-controls/ros2_control/pull/1358) is merged!

I don't see any specific reason to wait for that, as this PR removes long-deprecated mechanisms and is in line with the docs again, but sure, it's not necessarily required before https://github.com/ros-controls/ros2_control/pull/1358 is merged.

2024-03-03 10:33 UTC, saikishor commented
Sure, we can merge it. You have a point 👍🏽

2024-03-03 18:22 UTC, christophfroehlich approved these changes
LGTM, thank you for thinking of this! 
should we backport this? this should work even with humble?

2024-03-03 18:23 UTC, merged

2024-03-03 19:28 UTC, fmauch commented
No, this will not work on humble because we subscribe to robot_description and not ~/robot_description on rolling.