Add demo nodes
ros-controls/ros2_control_demos pull request #53
Opened 2021-01-13 14:42 UTC by destogl

2021-01-13 20:30 UTC, livanov93 approved these changes

2021-01-13 20:34 UTC, livanov93 requested changes

2021-01-13 20:34 UTC, livanov93 commented on ros2_control_demo_nodes/launch/rrbot_test_forward_position_controller.launch.py
> +    ])
Add empty line on the end

2021-01-13 20:34 UTC, livanov93 commented on ros2_control_demos/package.xml
>    <export>
Could also use an empty line on the end of the file.

2021-01-13 20:36 UTC, livanov93 approved these changes

2021-01-13 20:36 UTC, livanov93 approved these changes

2021-01-13 20:36 UTC, livanov93 approved these changes

2021-02-23 14:17 UTC, destogl commented
Will be replaced with multiple PRs.

2021-02-23 14:17 UTC, closed without merging