Refactor logging (backport #543)
ros-controls/ros2_control_demos pull request #619
Opened 2024-11-02 21:54 UTC by christophfroehlich

#543 with additional local variables/methods for logging, which are available from jazzy on only.

2024-11-02 21:55 UTC, christophfroehlich commented
@mergifyio backport iron

2024-11-13 07:35 UTC, saikishor requested changes

2024-11-13 07:35 UTC, saikishor commented on example_14/hardware/rrbot_actuator_without_feedback.cpp
> +    RCLCPP_INFO(get_logger(), ss.str().c_str());
@christophfroehlich is throttle missing here?

2024-11-13 07:35 UTC, saikishor commented on example_14/hardware/rrbot_sensor_for_position_feedback.cpp
> +  RCLCPP_INFO(get_logger(), ss.str().c_str());
@christophfroehlich here as well?

2024-11-13 07:35 UTC, saikishor commented on example_6/hardware/rrbot_actuator.cpp
> +  RCLCPP_INFO(get_logger(), "%s", ss.str().c_str());
missing throttle here

2024-11-13 07:35 UTC, saikishor commented on example_6/hardware/rrbot_actuator.cpp
> +  RCLCPP_INFO(get_logger(), "%s", ss.str().c_str());
missing throttle here

2024-11-13 07:43 UTC, christophfroehlich commented
@saikishor we have the problems with throttling in the plugins, remember https://github.com/ros-controls/ros2_control_demos/pull/603 ;)

2024-11-13 07:48 UTC, saikishor approved these changes
You are right! Looks good to me

2024-11-13 10:34 UTC, merged